### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by sousawalker** [leptoquark1/ng-time-past-pipe#10]
How can i change language?

**Comment by leptoquark1** [comment]
Hey @sousawalker,

have you tried to [overwrite the result output ](https://github.com/leptoquark1/ng-time-past-pipe#overwrite-the-result-output) by providing your own `CUSTOM_TIME_DIFF_GENERATOR`?

You can take the [original generator function](https://github.com/leptoquark1/ng-time-past-pipe/blob/master/projects/ng-time-past-pipe/src/lib/time-diff.ts#L41-L81) as an example.

Currently I see no other solution for customizing the language output

**Comment by sousawalker** [comment]
Nice, i translate it. Now i have other problem:

![image](https://user-images.githubusercontent.com/1927838/127878872-2ecd02f0-3456-4582-b154-a32ddddfb908.png)

Can you fix it?

**Comment by sousawalker** [comment]
https://angular.io/errors/NG0100

**Comment by leptoquark1** [comment]
Can you please provide a reproducible example on [Plunker](http://plnkr.co/)?

**Comment by leptoquark1** [comment]
Closing this. Hope you fixed your Problem! If not please create a new issue
